### ISSUE TITLE
Malformed descriptions and 'long' description

### ISSUE THREAD

**Issue by wridgers** [yearbook/extendscript-api-documentation#12]
Occasionally the description fields are malformed. This stems from the XML -> JSON conversion since occasionally the description XML fields contain inline HTML. The best solution would be to strip out HTML before converting to JSON.

Further, currently the docs only display the 'short' description field. It would appear that 95% of the documentation only has a 'short' description, but I have come across a few 'long' description fields. It would be good to include these.

**Comment by tinne** [comment]
1. At least all text nodes in the short description must be rendered.
2. Better yet, the long descriptions should follow, although this could be weighted against performance (cf. #3)
3. Furthermore, there are value fields to enumerations (like the PhotoShop ColorModel constants), which are part of the JSON, but missing from the HTML output. They could be part of the field divisions, as in 
> int **GRAYSCALE** = 1
