### ISSUE TITLE
Site is no longer live

### ISSUE THREAD

**Issue by alexwidener** [yearbook/extendscript-api-documentation#14]
Going to the url of http://yearbookmachine.github.io/indesign results in a 404.

**Comment by wridgers** [comment]
Ah yes, this is because we changed our github username from yearbookmachine to yearbook.

I will fix this!

**Comment by alexwidener** [comment]
I'm unsure if you meant that you would fix the listing on the page or the actual URL - going to yearbook.github.io still doesn't work, thought you should know just in case.

**Comment by danbarker** [comment]
Hi Alex,

Thanks for the report. I looked in to this a couple of days ago too and it
looks like we're going to have to recreate the repo as GitHub don't seem to
properly port across the GitHub Pages when you change the account name.
We'll get it sorted ASAP.

Dan

**Comment by wridgers** [comment]
The site is up now: http://yearbook.github.io/esdocs/

Perhaps we should setup a redirect here: https://yearbookmachine.github.io/esdocs/#/ ?

I couldn't see anything wrong with our setup so I contact GH support. Apparently you need to make a new commit to master to trigger a page build.

**Comment by wridgers** [comment]
Okay, I've setup a page letting everyone know that we've moved the documentation too!

http://yearbookmachine.github.io/esdocs/

**Comment by alexwidener** [comment]
Glad it's back! I've been lost without it :)
