### ISSUE TITLE
Links to precompiled Library files are invalid

### ISSUE THREAD

**Issue by fyrye** [yearbook/extendscript-api-documentation#15]
They are referencing the old yearbookmachine.github.io domain name - http://yearbookmachine.github.io/esdocs/ybm-esapi-docs.zip.
This includes the [README.md](https://github.com/yearbook/extendscript-api-documentation/blob/master/README.md) and the [Generated API Documention](http://yearbook.github.io/esdocs/#/) and should be updated to http://yearbook.github.io/esdocs/ybm-esapi-docs.zip

**Comment by wridgers** [comment]
Good catch. I'll fix this. Thanks!

**Comment by wridgers** [comment]
This should be fixed now, although it might take a while for the github.io pages to update.
