### ISSUE TITLE
 javascript and scriptui xml source files for local build

### ISSUE THREAD

**Issue by sushidub** [yearbook/extendscript-api-documentation#36]
Not an issue. Not an enhancement. Not a bug. Not a feature request.

Just a simple call for a donated copy of `javascript.xml` and `scriptui.xml`. These would be normally be found in `/Library/Application\ Support/Adobe/Scripting\ Dictionaries\ CC/CommonFiles/` of which does not exist on my machine.

_Why?_

Because I don't have a local copy of the javascript or scriptui xml source files. They're not in any of my library folders. `find` doesn't locate anything either. Almost sure they disappeared when I had to uninstall ExtendScript IDE to install Catalina on the macbook.
I do have everything else I need however. Build runs great too.
Thanks in advance and nice work!

**Comment by danbarker** [comment]
Hi Jeremy, if you can provide an email address I can send them over to you. I had the same issue as you last year (see here: https://github.com/yearbook/extendscript-api-documentation/pull/26 ) but apparently eventually managed to find them, I think perhaps by reinstalling CC Toolkit on a Mojave machine, or perhaps on Windows

**Comment by danbarker** [comment]
Sent to your gmail

**Comment by sushidub** [comment]
> re: @danbarker

Thanks Dan ~ 
I came back here to close the issue just now (got creative with an old .dmg installer of ExtendScript and managed to extract both files), lo and behold all I had to do was check my inbox.
Good times. ;)
